//go:build ignore

package main

import (
	"bytes"
	"log"
	"os"
	"regexp"

	"github.com/nextask/nextask/internal/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func main() {
	outFile := "./doc/CLI.md"
	if len(os.Args) > 1 {
		outFile = os.Args[1]
	}

	f, err := os.Create(outFile)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	f.WriteString("# CLI Reference\n\n")

	genCmd(f, cli.RootCmd)
	for _, cmd := range cli.RootCmd.Commands() {
		if cmd.Name() == "help" || cmd.Name() == "completion" {
			continue
		}
		genCmd(f, cmd)
		for _, sub := range cmd.Commands() {
			if sub.Name() == "help" {
				continue
			}
			genCmd(f, sub)
		}
	}

	f.WriteString("\n---\n\n###### Auto generated by spf13/cobra\n")
}

var autoGenRe = regexp.MustCompile(`(?m)^###### Auto generated.*\n`)
var seeAlsoRe = regexp.MustCompile(`(?ms)^### SEE ALSO\n.*?(\n---|\n###### Auto|\z)`)

func genCmd(f *os.File, cmd *cobra.Command) {
	var buf bytes.Buffer
	doc.GenMarkdown(cmd, &buf)
	clean := autoGenRe.ReplaceAll(buf.Bytes(), nil)
	clean = seeAlsoRe.ReplaceAll(clean, nil)
	f.WriteString("---\n\n")
	f.Write(clean)
}
